#! /bin/sh

PROCESS_ID=$(ps x | grep 'node server-ssr.ts' | grep -v grep | awk '{print $1}')
if [ -z "$PROCESS_ID" ];
then
    nohup pnpm cross-env NODE_ENV=production node server-ssr.ts > log/$(date +"%Y-%m-%d_%H-%M-%S").log 2>&1 &
else
    echo "Server is already running"
fi
