#! /bin/sh

PROCESS_ID=$(ps x | grep 'node server-ssr.ts' | grep -v grep | awk '{print $1}')
if [ ! -z "$PROCESS_ID" ];
then
    pkill -9 -f 'node server-ssr.ts'
else
    echo "Server is not running"
fi
